using Avalonia.Input;
using Key = Silk.NET.Input.Key;

namespace QuickGraphics.AvaloniaQg;

public static class KeyboardExtensions
{
    public static Key ToSilkKey(this PhysicalKey key)
    {
        return key switch
        {
            PhysicalKey.None => Key.Unknown,

            // Writing System Keys
            PhysicalKey.Backquote => Key.Apostrophe,
            PhysicalKey.Backslash => Key.BackSlash,
            PhysicalKey.BracketLeft => Key.LeftBracket,
            PhysicalKey.BracketRight => Key.RightBracket,
            PhysicalKey.Comma => Key.Comma,
            PhysicalKey.Digit0 => Key.Number0,
            PhysicalKey.Digit1 => Key.Number1,
            PhysicalKey.Digit2 => Key.Number2,
            PhysicalKey.Digit3 => Key.Number3,
            PhysicalKey.Digit4 => Key.Number4,
            PhysicalKey.Digit5 => Key.Number5,
            PhysicalKey.Digit6 => Key.Number6,
            PhysicalKey.Digit7 => Key.Number7,
            PhysicalKey.Digit8 => Key.Number8,
            PhysicalKey.Digit9 => Key.Number9,
            PhysicalKey.Equal => Key.Equal,
            // PhysicalKey.IntlBackslash => Key.Oem102,
            // PhysicalKey.IntlRo => Key.Oem102,
            // PhysicalKey.IntlYen => Key.Oem5,
            PhysicalKey.A => Key.A,
            PhysicalKey.B => Key.B,
            PhysicalKey.C => Key.C,
            PhysicalKey.D => Key.D,
            PhysicalKey.E => Key.E,
            PhysicalKey.F => Key.F,
            PhysicalKey.G => Key.G,
            PhysicalKey.H => Key.H,
            PhysicalKey.I => Key.I,
            PhysicalKey.J => Key.J,
            PhysicalKey.K => Key.K,
            PhysicalKey.L => Key.L,
            PhysicalKey.M => Key.M,
            PhysicalKey.N => Key.N,
            PhysicalKey.O => Key.O,
            PhysicalKey.P => Key.P,
            PhysicalKey.Q => Key.Q,
            PhysicalKey.R => Key.R,
            PhysicalKey.S => Key.S,
            PhysicalKey.T => Key.T,
            PhysicalKey.U => Key.U,
            PhysicalKey.V => Key.V,
            PhysicalKey.W => Key.W,
            PhysicalKey.X => Key.X,
            PhysicalKey.Y => Key.Y,
            PhysicalKey.Z => Key.Z,
            PhysicalKey.Minus => Key.Minus,
            PhysicalKey.Period => Key.Period,
            // PhysicalKey.Quote => Key.Oem7,
            PhysicalKey.Semicolon => Key.Semicolon,
            PhysicalKey.Slash => Key.Slash,

            // Functional Keys
            PhysicalKey.AltLeft => Key.AltLeft,
            PhysicalKey.AltRight => Key.AltRight,
            PhysicalKey.Backspace => Key.Backspace,
            PhysicalKey.CapsLock => Key.CapsLock,
            PhysicalKey.ContextMenu => Key.Menu,
            PhysicalKey.ControlLeft => Key.ControlLeft,
            PhysicalKey.ControlRight => Key.ControlRight,
            PhysicalKey.Enter => Key.Enter,
            PhysicalKey.MetaLeft => Key.SuperLeft,
            PhysicalKey.MetaRight => Key.SuperRight,
            PhysicalKey.ShiftLeft => Key.ShiftLeft,
            PhysicalKey.ShiftRight => Key.ShiftRight,
            PhysicalKey.Space => Key.Space,
            PhysicalKey.Tab => Key.Tab,
            // PhysicalKey.Convert => Key.ImeConvert,
            // PhysicalKey.KanaMode => Key.KanaMode,
            // PhysicalKey.Lang1 => Key.HangulMode,
            // PhysicalKey.Lang2 => Key.HanjaMode,
            // PhysicalKey.Lang3 => Key.DbeKatakana,
            // PhysicalKey.Lang4 => Key.DbeHiragana,
            // PhysicalKey.Lang5 => Key.OemAuto,
            // PhysicalKey.NonConvert => Key.ImeNonConvert,

            // Control Pad Section
            PhysicalKey.Delete => Key.Delete,
            PhysicalKey.End => Key.End,
            // PhysicalKey.Help => Key.Help,
            PhysicalKey.Home => Key.Home,
            PhysicalKey.Insert => Key.Insert,
            PhysicalKey.PageDown => Key.PageDown,
            PhysicalKey.PageUp => Key.PageUp,

            // Arrow Pad Section
            PhysicalKey.ArrowDown => Key.Down,
            PhysicalKey.ArrowLeft => Key.Left,
            PhysicalKey.ArrowRight => Key.Right,
            PhysicalKey.ArrowUp => Key.Up,

            // Numpad Section
            PhysicalKey.NumLock => Key.NumLock,
            PhysicalKey.NumPad0 => Key.Keypad0,
            PhysicalKey.NumPad1 => Key.Keypad1,
            PhysicalKey.NumPad2 => Key.Keypad2,
            PhysicalKey.NumPad3 => Key.Keypad3,
            PhysicalKey.NumPad4 => Key.Keypad4,
            PhysicalKey.NumPad5 => Key.Keypad5,
            PhysicalKey.NumPad6 => Key.Keypad6,
            PhysicalKey.NumPad7 => Key.Keypad7,
            PhysicalKey.NumPad8 => Key.Keypad8,
            PhysicalKey.NumPad9 => Key.Keypad9,
            PhysicalKey.NumPadAdd => Key.KeypadAdd,
            // PhysicalKey.NumPadClear => Key.Clear,
            // PhysicalKey.NumPadComma => Key.AbntC2,
            PhysicalKey.NumPadDecimal => Key.KeypadDecimal,
            PhysicalKey.NumPadDivide => Key.KeypadDivide,
            PhysicalKey.NumPadEnter => Key.KeypadEnter,
            PhysicalKey.NumPadEqual => Key.KeypadAdd,
            PhysicalKey.NumPadMultiply => Key.KeypadMultiply,
            // PhysicalKey.NumPadParenLeft => Key.Oem4,
            // PhysicalKey.NumPadParenRight => Key.Oem6,
            PhysicalKey.NumPadSubtract => Key.KeypadSubtract,

            // Function Section
            PhysicalKey.Escape => Key.Escape,
            PhysicalKey.F1 => Key.F1,
            PhysicalKey.F2 => Key.F2,
            PhysicalKey.F3 => Key.F3,
            PhysicalKey.F4 => Key.F4,
            PhysicalKey.F5 => Key.F5,
            PhysicalKey.F6 => Key.F6,
            PhysicalKey.F7 => Key.F7,
            PhysicalKey.F8 => Key.F8,
            PhysicalKey.F9 => Key.F9,
            PhysicalKey.F10 => Key.F10,
            PhysicalKey.F11 => Key.F11,
            PhysicalKey.F12 => Key.F12,
            PhysicalKey.F13 => Key.F13,
            PhysicalKey.F14 => Key.F14,
            PhysicalKey.F15 => Key.F15,
            PhysicalKey.F16 => Key.F16,
            PhysicalKey.F17 => Key.F17,
            PhysicalKey.F18 => Key.F18,
            PhysicalKey.F19 => Key.F19,
            PhysicalKey.F20 => Key.F20,
            PhysicalKey.F21 => Key.F21,
            PhysicalKey.F22 => Key.F22,
            PhysicalKey.F23 => Key.F23,
            PhysicalKey.F24 => Key.F24,
            PhysicalKey.PrintScreen => Key.PrintScreen,
            PhysicalKey.ScrollLock => Key.ScrollLock,
            PhysicalKey.Pause => Key.Pause,

            // Media Keys
            // PhysicalKey.BrowserBack => Key.BrowserBack,
            // PhysicalKey.BrowserFavorites => Key.BrowserFavorites,
            // PhysicalKey.BrowserForward => Key.BrowserForward,
            // PhysicalKey.BrowserHome => Key.BrowserHome,
            // PhysicalKey.BrowserRefresh => Key.BrowserRefresh,
            // PhysicalKey.BrowserSearch => Key.BrowserSearch,
            // PhysicalKey.BrowserStop => Key.BrowserStop,
            // PhysicalKey.Eject => Key.None,
            // PhysicalKey.LaunchApp1 => Key.LaunchApplication1,
            // PhysicalKey.LaunchApp2 => Key.LaunchApplication2,
            // PhysicalKey.LaunchMail => Key.LaunchMail,
            // PhysicalKey.MediaPlayPause => Key.MediaPlayPause,
            // PhysicalKey.MediaSelect => Key.SelectMedia,
            // PhysicalKey.MediaStop => Key.MediaStop,
            // PhysicalKey.MediaTrackNext => Key.MediaNextTrack,
            // PhysicalKey.MediaTrackPrevious => Key.MediaPreviousTrack,
            // PhysicalKey.Power => Key.None,
            // PhysicalKey.Sleep => Key.Sleep,
            // PhysicalKey.AudioVolumeDown => Key.VolumeDown,
            // PhysicalKey.AudioVolumeMute => Key.VolumeMute,
            // PhysicalKey.AudioVolumeUp => Key.VolumeUp,
            // PhysicalKey.WakeUp => Key.None,

            // Legacy Keys
            // PhysicalKey.Again => Key.None,
            // PhysicalKey.Copy => Key.OemCopy,
            // PhysicalKey.Cut => Key.None,
            // PhysicalKey.Find => Key.None,
            // PhysicalKey.Open => Key.None,
            // PhysicalKey.Paste => Key.None,
            // PhysicalKey.Props => Key.None,
            // PhysicalKey.Select => Key.Select,
            // PhysicalKey.Undo => Key.None,

            _ => Key.Unknown
        };
    }
}
